import {StyleSheet} from 'react-native';
// import DeviceInfo from 'react-native-device-info';

import {Fonts, Colors} from '../../styles';

export default StyleSheet.create({
  content: {
    justifyContent: 'center',
    marginBottom: 100,
    marginRight: 30,
    marginLeft: 30,
    // backgroundColor: 'red'
  },
  container: {
    flex: 1,
    backgroundColor: Colors.White,
  },
  head: {
    height: 40,
    backgroundColor: '#f1f8ff',
  },
  wrapper: {
    flexDirection: 'row',
  },
  title: {
    flex: 1,
    backgroundColor: '#f6f8fa',
  },
  row: {
    height: 28,
  },
  text: {
    textAlign: 'left',
  },
  scrollListContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'stretch',
  },
  tableContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 5,
    //marginLeft: -3,
    //alignContent: 'center',
    //alignSelf: 'center',
    //alignItems: 'center',
    //textAlign: 'center',
    width: '100%',
    // borderBottomWidth: 1,
    // borderBottomColor: 'grey',
  },
  tableContainerDetail: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 5,
    //marginLeft: -3,
    //alignContent: 'center',
    //alignSelf: 'center',
    //alignItems: 'center',
    //textAlign: 'center',
    width: '100%',
    // borderBottomWidth: 1,
    // borderBottomColor: 'grey',
  },
  buttonContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 5,
    marginLeft: 5,
    //alignContent: 'center',
    //alignSelf: 'center',
    //alignItems: 'center',
    //textAlign: 'center',
    width: '100%',
    // borderBottomWidth: 1,
    // borderBottomColor: 'grey',
  },
  buttonContainerFooter: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 5,
    //marginLeft: 30,
    width: '100%',
  },
  rightButtonFooter: {
    height: 10,
    backgroundColor: '#2a7050',
    width: 100,
    alignSelf: 'center',
    alignItems: 'center',
    alignContent: 'center',
  },
  table: {
    borderWidth: 1,
    borderTopColor: '#2a7050',
    borderTopWidth: 2,
    borderBottomColor: '#2a7050',
    borderBottomWidth: 2,
  },
  tableLeft: {
    borderTopColor: '#2a7050',
    borderTopWidth: 1,
    borderBottomColor: '#eff0ef',
    borderBottomWidth: 5,
  },
  SubListDetail: {
    marginLeft: -5,
    marginRight: -5,
  },
  tableRight: {
    borderTopColor: '#2a7050',
    borderTopWidth: 1,
    borderBottomColor: '#eff0ef',
    borderBottomWidth: 5,
    marginLeft: -2,
  },
  tableRightDetail: {
    borderTopColor: '#2a7050',
    borderTopWidth: 1,
    borderBottomColor: '#eff0ef',
    borderBottomWidth: 5,
    marginLeft: -2,
  },
  tableBorder: {
    borderColor: 'transparent',
  },
  tableRowEven: {
    backgroundColor: '#eff0ef',
  },
  tableRowText: {
    fontSize: 12,
    color: '#2a7050',
  },
  tableRowValue: {
    fontSize: 12,
  },
  tableRowHeader: {
    backgroundColor: '#2a7050',
    height: 8,
  },
  tableRowHeaderDetail: {
    backgroundColor: '#d3e0d9',
    height: 4,
  },
  tableRowFooter: {
    backgroundColor: '#eff0ef',
    height: 3,
  },
  tableDetailButton: {
    height: 25,
    backgroundColor: '#2a7050',
    width: 100,
    marginTop: 100,
    marginLeft: -45,
  },
  profileContainer: {
    marginTop: -60,
    position: 'relative',
    justifyContent: 'center',
    alignSelf: 'center',
    width: '92%',
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    elevation: 2,
  },
  profileContainerBox: {
    flexDirection: 'row',
    paddingBottom: '5%',
    paddingLeft: '5%',
    paddingRight: '5%',
    justifyContent: 'space-between',
  },
  profileHeader: {
    marginTop: 0,
    position: 'relative',
    justifyContent: 'center',
    alignSelf: 'center',
    width: '100%',
    height: 70,
    flex: 1,
    //borderRadius: 10,
    backgroundColor: '#2a7050',
    elevation: 2,
  },
  footerText: {
    color: 'white',
    textAlign: 'right',
    textAlignVertical: 'center',
    // paddingRight: DeviceInfo.hasNotch() ? 20 : 5,
    fontSize: 10,
  },
  profileInfoContainer: {
    marginTop: -30,
    //marginLeft : 10,
    height: 25,
  },
  profileInfoItem: {
    borderBottomWidth: 0,
    alignContent: 'center',
    alignSelf: 'center',
    width: '80%',
  },
  headerDate: {
    fontSize: Fonts.Large,
    fontWeight: '500',
    color: '#1a1919',
  },
  headerContentContainer: {
    borderBottomWidth: 0,
    backgroundColor: Colors.White,
    alignSelf: 'center',
    alignItems: 'center',
    alignContent: 'center',
    width: '90%',
  },
  headerContentSeparator: {
    fontSize: 20,
    fontWeight: '200',
    color: Colors.White,
  },
  headerContentTitle: {
    fontSize: 11,
    fontWeight: '300',
    color: '#1a1919',
    textAlign: 'center',
  },
  headerContentValue: {
    fontSize: 28,
    fontWeight: '800',
    color: '#2a7050',
    paddingBottom: 10,
    textAlign: 'center',
  },
  rightButton: {
    height: 25,
    backgroundColor: '#2a7050',
    width: 130,
    alignSelf: 'center',
    alignItems: 'center',
    alignContent: 'center',
  },
  headerContentDetailButton: {
    height: 25,
    backgroundColor: '#2a7050',
    width: 130,
    alignSelf: 'center',
    alignItems: 'center',
    alignContent: 'center',
  },
  headerContentDetailText: {
    fontSize: 12,
    fontWeight: '400',
    color: 'white',
  },
  footerContentTitle: {
    fontSize: Fonts.Medium,
    fontWeight: '400',
    color: '#1a1919',
    textAlign: 'left',
  },
  profileTitle: {
    fontSize: Fonts.Medium,
    fontWeight: '300',
    color: '#1a1919',
  },
  profileImage: {
    height: 75,
    width: 75,
    resizeMode: 'stretch',
  },
  menuContainerBoxHeader: {
    marginTop: 20,
    alignContent: 'center',
    alignSelf: 'center',
  },
  menuContainerBoxContent: {
    // marginTop: 10,
    paddingTop: 20,
    marginBottom: 100,
    alignContent: 'center',
    alignSelf: 'center',
    width: '100%',
    height: '100%',
    // paddingBottom: 10,
    // backgroundColor: 'red'
  },
  menuContainerBox: {
    paddingTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    flexWrap: 'wrap',
    flex: 1,
  },
  menuItemContainer: {
    marginTop: 20,
    alignContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    textAlign: 'center',
    width: '100%',
    // borderBottomWidth: 1,
    // borderBottomColor: 'grey',
  },
  menuItem: {
    paddingTop: 5,
    paddingBottom: 5,
    //paddingLeft: '4%',
    width: '50%',
  },
  menuTitle: {
    fontSize: Fonts.Medium,
    fontWeight: '500',
    color: '#1a1919',
    textAlign: 'center',
    paddingRight: 25,
  },
  menuTitleLog: {
    fontSize: Fonts.Medium,
    fontWeight: '500',
    color: '#1a1919',
    textAlign: 'center',
    marginLeft: -25,
  },
  menuImage: {
    height: 110,
    width: 110,
    resizeMode: 'stretch',
  },
});

export const headerStyles = {
  headerStyle: {
    backgroundColor: Colors.Primary,
  },
};
